[package]
name = "nft-on-chain"
version = "0.0.0"
authors = [ "Skyzox",]
edition = "2018"
publish = false

[lib]
path = "src/empty.rs"

[dev-dependencies]
num-bigint = "0.4.2"

[dependencies.elrond-wasm]
version = "0.29.3"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.3"
