[package]
name = "nft-on-chain-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Skyzox"]

[dev-dependencies]

[dependencies.nft-on-chain]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.29.3"
