[package]
name = "nft-with-on-chain-attributs-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Skyzox"]

[dev-dependencies]

[dependencies.nft-with-on-chain-attributs]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.29.3"
